<?php

declare(strict_types=1);

namespace SilverStripe\Omnipay\Tests;

use SilverStripe\Omnipay\Service\AuthorizeService;
use SilverStripe\Omnipay\Service\PurchaseService;
use SilverStripe\Omnipay\Service\CaptureService;
use SilverStripe\Core\Config\Config;
use SilverStripe\Dev\FunctionalTest;
use SilverStripe\Omnipay\Exception\InvalidConfigurationException;
use SilverStripe\Omnipay\GatewayInfo;
use SilverStripe\Omnipay\Model\Payment;
use SilverStripe\Omnipay\Service\ServiceFactory;
use SilverStripe\Omnipay\Tests\Extensions\ServiceFactoryTestExtension;
use SilverStripe\Omnipay\Tests\Extensions\ServiceFactoryTestExtensionTwo;
use SilverStripe\Omnipay\Tests\Service\ServiceFactoryTestService;

class ServiceFactoryTest extends FunctionalTest
{
    use PaymentTestTrait;

    protected static $fixture_file = 'PaymentTest.yml';

    protected $autoFollowRedirection = false;

    private static array $dependencies = [
        ServiceFactoryTestService::class
    ];


    public function testDefaultServices(): void
    {
        $payment = Payment::create()
            ->setGateway("PaymentExpress_PxPay")
            ->setAmount(123)
            ->setCurrency("GBP");

        //$this->setExpectException(InvalidConfigurationException::class);
        $this->assertInstanceOf(
            AuthorizeService::class,
            $this->factory->getService($payment, ServiceFactory::INTENT_AUTHORIZE),
            'Intent "authorize" should return an instance of "AuthorizeService".'
        );

        $this->assertInstanceOf(
            PurchaseService::class,
            $this->factory->getService($payment, ServiceFactory::INTENT_PAYMENT),
            'Intent "payment" must return a PurchaseService when gateway doesn\'t use authorize.'
        );

        Config::modify()->merge(GatewayInfo::class, 'PaymentExpress_PxPay', [
            'use_authorize' => true
        ]);

        $this->assertInstanceOf(
            AuthorizeService::class,
            $this->factory->getService($payment, ServiceFactory::INTENT_PAYMENT),
            'Intent "payment" must return a AuthorizeService when gateway is configured to use authorize.'
        );

        // This will throw an exception, because there's no service for the intent "undefined"
        $this->expectException(InvalidConfigurationException::class);
        $this->factory->getService($this->payment, 'undefined');
    }

    public function testCustomService(): void
    {
        Config::modify()->merge(ServiceFactory::class, 'services', [
            'purchase' => ServiceFactoryTestService::class
        ]);

        $this->assertInstanceOf(
            ServiceFactoryTestService::class,
            $this->factory->getService($this->payment, ServiceFactory::INTENT_PURCHASE),
            'The factory should return the configured service instead of the default one.'
        );

        ServiceFactory::add_extension(ServiceFactoryTestExtension::class);
        ServiceFactory::add_extension(ServiceFactoryTestExtensionTwo::class);

        // create a new factory instance that uses the new extensions
        $serviceFactory = ServiceFactory::create();

        $serviceFactory->getService($this->payment, ServiceFactory::INTENT_PURCHASE);

        // the extension will now take care of creating the purchase service
        $this->assertInstanceOf(
            CaptureService::class,
            $serviceFactory->getService($this->payment, ServiceFactory::INTENT_PURCHASE),
            'The factory should return the service generated by the extension.'
        );

        // by having a correctly named method on the extension, 'test' is a valid intent
        $this->assertInstanceOf(
            ServiceFactoryTestService::class,
            $serviceFactory->getService($this->payment, 'test'),
            'The extension should create a ServiceFactoryTest_TestService instance for the "test" intent.'
        );

        $catched = null;
        try {
            // this should throw an exception since two extensions try to create a service
            $serviceFactory->getService($this->payment, ServiceFactory::INTENT_AUTHORIZE);
        } catch (InvalidConfigurationException $invalidConfigurationException) {
            $catched = $invalidConfigurationException;
        }

        $this->assertInstanceOf(
            InvalidConfigurationException::class,
            $catched,
            'When two extensions create service instances, an exception should be raised.'
        );
    }
}
