---
Name: OmnipayDevelopmentAdmin
After: DevelopmentAdmin
---
SilverStripe\Dev\DevelopmentAdmin:
  controllers:
    payment:
      class: SilverStripe\Omnipay\Admin\PaymentDevelopmentAdmin
      description: 'Show Payment configuration information'
